
package za.ac.nwu.wsdl.studentacademicregistration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentAcademicRegistrationService", targetNamespace = "http://nwu.ac.za/wsdl/StudentAcademicRegistration", wsdlLocation = "http://workflowprd.nwu.ac.za/sapi-vss-v5/StudentAcademicRegistrationService/StudentAcademicRegistrationService?wsdl")
public class StudentAcademicRegistrationService_Service
    extends Service
{

    private final static URL STUDENTACADEMICREGISTRATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTACADEMICREGISTRATIONSERVICE_EXCEPTION;
    private final static QName STUDENTACADEMICREGISTRATIONSERVICE_QNAME = new QName("http://nwu.ac.za/wsdl/StudentAcademicRegistration", "StudentAcademicRegistrationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://workflowprd.nwu.ac.za/sapi-vss-v5/StudentAcademicRegistrationService/StudentAcademicRegistrationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTACADEMICREGISTRATIONSERVICE_WSDL_LOCATION = url;
        STUDENTACADEMICREGISTRATIONSERVICE_EXCEPTION = e;
    }

    public StudentAcademicRegistrationService_Service() {
        super(__getWsdlLocation(), STUDENTACADEMICREGISTRATIONSERVICE_QNAME);
    }

    public StudentAcademicRegistrationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTACADEMICREGISTRATIONSERVICE_QNAME, features);
    }

    public StudentAcademicRegistrationService_Service(URL wsdlLocation) {
        super(wsdlLocation, STUDENTACADEMICREGISTRATIONSERVICE_QNAME);
    }

    public StudentAcademicRegistrationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTACADEMICREGISTRATIONSERVICE_QNAME, features);
    }

    public StudentAcademicRegistrationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentAcademicRegistrationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentAcademicRegistrationService
     */
    @WebEndpoint(name = "StudentAcademicRegistrationServicePort")
    public StudentAcademicRegistrationService getStudentAcademicRegistrationServicePort() {
        return super.getPort(new QName("http://nwu.ac.za/wsdl/StudentAcademicRegistration", "StudentAcademicRegistrationServicePort"), StudentAcademicRegistrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentAcademicRegistrationService
     */
    @WebEndpoint(name = "StudentAcademicRegistrationServicePort")
    public StudentAcademicRegistrationService getStudentAcademicRegistrationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://nwu.ac.za/wsdl/StudentAcademicRegistration", "StudentAcademicRegistrationServicePort"), StudentAcademicRegistrationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTACADEMICREGISTRATIONSERVICE_EXCEPTION!= null) {
            throw STUDENTACADEMICREGISTRATIONSERVICE_EXCEPTION;
        }
        return STUDENTACADEMICREGISTRATIONSERVICE_WSDL_LOCATION;
    }

}
